//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsCargaHoras {
    
    public partial class AyudaTareasNet {
    }
}


