//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsCargaHoras {
    
    public partial class Kanban {
        
        /// <summary>
        /// Control txtLegajo.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLegajo;
        
        /// <summary>
        /// Control ddlFuente.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFuente;
        
        /// <summary>
        /// Control btnAplicar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAplicar;
        
        /// <summary>
        /// Control upKanban.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upKanban;
        
        /// <summary>
        /// Control dsKanban.
        /// </summary>
        protected global::System.Web.UI.WebControls.SqlDataSource dsKanban;
        
        /// <summary>
        /// Control rptItems.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptItems;
        
        /// <summary>
        /// Control grdTrac.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView grdTrac;

        /// <summary>
        /// Control hidUserKey.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hidUserKey;
    }
}


