//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsCargaHoras
{


    public partial class SiteMaster
    {

        /// <summary>
        /// Control HeadContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Control MainContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// Control lblNavbarNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavbarNombre;

        /// <summary>
        /// Control lblNavbarLegajo.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblNavbarLegajo;

        /// <summary>
        /// Control lblUserNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserNombre;

        /// <summary>
        /// Control lblUserLegajo.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserLegajo;

        /// <summary>
        /// Control lblUserUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserUsuario;

        /// <summary>
        /// Control lblUserMail.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUserMail;
    }
}
