//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsCargaHoras {
    
    public partial class TestLABTRAC {
        
        protected global::System.Web.UI.WebControls.Label lblStatus;
        
        protected global::System.Web.UI.WebControls.TextBox txtQuery;
        
        protected global::System.Web.UI.WebControls.Button btnRun;
        
        protected global::System.Web.UI.WebControls.GridView grid;
    }
}


